<?php

declare(strict_types=1);

namespace Generated\Model;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator dev-main (<normalized timestamp>)
 */

class CatalogItem
{
    public string $sku;
    public string $name;
    public ?Money $price = null;

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromArray(array $data): CatalogItem
    {
        $instance = new CatalogItem(
            sku: $data['sku'] ?? '',
            name: $data['name'] ?? '',
            price: isset($data['price']) ? Money::fromArray($data['price']) : null,
        );

        return $instance;
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromRequestArray(array $data): CatalogItem
    {
        return CatalogItem::fromArray($data);
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromResponseArray(array $data): CatalogItem
    {
        return CatalogItem::fromArray($data);
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toArray(): array
    {
        $data = [];
        $data['sku'] = $this->sku;
        $data['name'] = $this->name;
        if ($this->price !== null) {
            $data['price'] = method_exists($this->price, 'toArray') ? $this->price->toArray() : $this->price;
        }

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toRequestArray(): array
    {
        $data = $this->toArray();

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toResponseArray(): array
    {
        $data = $this->toArray();

        return $data;
    }
}
