<?php

declare(strict_types=1);

namespace Generated\Model;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator dev-main (<normalized timestamp>)
 */

class CreateOrderRequest
{
    public Money $total;
    public ?string $notes = null;

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromArray(array $data): CreateOrderRequest
    {
        $instance = new CreateOrderRequest(
            total: isset($data['total']) ? Money::fromArray($data['total']) : Money::fromArray([]),
            notes: $data['notes'] ?? null,
        );

        return $instance;
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromRequestArray(array $data): CreateOrderRequest
    {
        return CreateOrderRequest::fromArray($data);
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromResponseArray(array $data): CreateOrderRequest
    {
        return CreateOrderRequest::fromArray($data);
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toArray(): array
    {
        $data = [];
        $data['total'] = method_exists($this->total, 'toArray') ? $this->total->toArray() : $this->total;
        if ($this->notes !== null) {
            $data['notes'] = $this->notes;
        }

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toRequestArray(): array
    {
        $data = $this->toArray();

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toResponseArray(): array
    {
        $data = $this->toArray();

        return $data;
    }
}
