<?php

declare(strict_types=1);

namespace Generated\Model;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator dev-main (<normalized timestamp>)
 */

/**
 * This schema is deprecated.
 * @deprecated
 */
class DeprecatedSchema
{
    public string $id;
    /**
     * @deprecated
     */
    public ?string $legacyField = null;

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromArray(array $data): DeprecatedSchema
    {
        $instance = new DeprecatedSchema(
            id: $data['id'] ?? '',
            legacyField: $data['legacyField'] ?? null,
        );

        return $instance;
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromRequestArray(array $data): DeprecatedSchema
    {
        return DeprecatedSchema::fromArray($data);
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromResponseArray(array $data): DeprecatedSchema
    {
        return DeprecatedSchema::fromArray($data);
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toArray(): array
    {
        $data = [];
        $data['id'] = $this->id;
        if ($this->legacyField !== null) {
            $data['legacyField'] = $this->legacyField;
        }

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toRequestArray(): array
    {
        $data = $this->toArray();

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toResponseArray(): array
    {
        $data = $this->toArray();

        return $data;
    }
}
