<?php

declare(strict_types=1);

namespace Generated\Model;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator dev-main (<normalized timestamp>)
 */

class PluginTestSchema
{
    public string $name;
    public string $password;

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromArray(array $data): PluginTestSchema
    {
        $instance = new PluginTestSchema(
            name: $data['name'] ?? '',
            password: $data['password'] ?? '',
        );

        return $instance;
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromRequestArray(array $data): PluginTestSchema
    {
        return PluginTestSchema::fromArray($data);
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromResponseArray(array $data): PluginTestSchema
    {
        return PluginTestSchema::fromArray($data);
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toArray(): array
    {
        $data = [];
        $data['name'] = $this->name;
        $data['password'] = $this->password;

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toRequestArray(): array
    {
        $data = $this->toArray();

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toResponseArray(): array
    {
        $data = $this->toArray();

        return $data;
    }
}
