<?php

declare(strict_types=1);

namespace Generated\Model;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator <normalized version> (<normalized timestamp>)
 */

readonly class ApiError
{
    public function __construct(
        public string $code,
        public string $message,
    ) {}

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromArray(array $data): ApiError
    {
        $instance = new ApiError(
            code: $data['code'] ?? '',
            message: $data['message'] ?? '',
        );

        return $instance;
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromRequestArray(array $data): ApiError
    {
        return ApiError::fromArray($data);
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromResponseArray(array $data): ApiError
    {
        return ApiError::fromArray($data);
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toArray(): array
    {
        $data = [];
        $data['code'] = $this->code;
        $data['message'] = $this->message;

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toRequestArray(): array
    {
        $data = $this->toArray();

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toResponseArray(): array
    {
        $data = $this->toArray();

        return $data;
    }
}
