<?php

declare(strict_types=1);

namespace Generated\Api;

use Generated\Model\CreateOrderRequest;
use Generated\Model\Order;
use Symfony\Contracts\HttpClient\HttpClientInterface;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator dev-main (<normalized timestamp>)
 */

final class OrdersApiClient implements OrdersApiClientInterface
{
    private function assertSuccessfulStatus(int $statusCode, string $operationId): void
    {
        if ($statusCode < 200 || $statusCode >= 300) {
            throw new \RuntimeException(sprintf(
                'API operation "%s" failed with HTTP status %d.',
                $operationId,
                $statusCode,
            ));
        }
    }

    private function decodeJsonResponse(string $contentType, string $body, string $operationId): mixed
    {
        if ($contentType !== '' && !str_contains(strtolower($contentType), 'json')) {
            throw new \UnexpectedValueException(sprintf(
                'Expected a JSON response for operation "%s", got content type "%s".',
                $operationId,
                $contentType,
            ));
        }

        try {
            return json_decode($body, true, 512, JSON_THROW_ON_ERROR);
        } catch (\JsonException $exception) {
            throw new \UnexpectedValueException(sprintf(
                'Invalid JSON response for operation "%s": %s',
                $operationId,
                $exception->getMessage(),
            ), 0, $exception);
        }
    }

    public function __construct(
        private readonly HttpClientInterface $httpClient,
        private readonly string $baseUrl,
    ) {}

    private function validateNativeRequestPayload(mixed $value): void
    {
        if (is_array($value)) {
            foreach ($value as $item) {
                $this->validateNativeRequestPayload($item);
            }

            return;
        }

        if (is_object($value)) {
            if (method_exists($value, 'validateOrThrowForRequest')) {
                $value->validateOrThrowForRequest();

                return;
            }

            if (method_exists($value, 'validateOrThrow')) {
                $value->validateOrThrow();
            }
        }
    }

    private function validateNativeResponsePayload(mixed $value): void
    {
        if (is_array($value)) {
            foreach ($value as $item) {
                $this->validateNativeResponsePayload($item);
            }

            return;
        }

        if (is_object($value)) {
            if (method_exists($value, 'validateOrThrowForResponse')) {
                $value->validateOrThrowForResponse();

                return;
            }

            if (method_exists($value, 'validateOrThrow')) {
                $value->validateOrThrow();
            }
        }
    }

    /**
     * Create an order
     */
    public function createOrder(CreateOrderRequest $body): Order
    {
        $this->validateNativeRequestPayload($body);
        $url = rtrim($this->baseUrl, '/') . '/orders';
        $response = $this->httpClient->request(
            'POST',
            $url,
            [
                'json' => $body->toRequestArray(),
            ],
        );
        $statusCode = $response->getStatusCode();
        $this->assertSuccessfulStatus($statusCode, 'createOrder');
        $data = $this->decodeJsonResponse($response->getHeaders(false)['content-type'][0] ?? '', $response->getContent(false), 'createOrder');
        if (!is_array($data)) {
            throw new \UnexpectedValueException('Expected a JSON object response for createOrder.');
        }
        $result = Order::fromResponseArray($data);
        $this->validateNativeResponsePayload($result);

        return $result;
    }
}
