<?php

declare(strict_types=1);

namespace Generated\Model;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator dev-main (<normalized timestamp>)
 */

readonly class Order
{
    public function __construct(
        public string $id,
        public OrderStatus $status,
        public Money $total,
        public ?Address $shippingAddress = null,
        public ?string $notes = null,
    ) {}

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromArray(array $data): Order
    {
        $instance = new Order(
            id: $data['id'] ?? '',
            status: isset($data['status'])
                ? (OrderStatus::fromArray($data['status']) ?? throw new \InvalidArgumentException('Unknown value for status.'))
                : throw new \InvalidArgumentException('Missing required property status.'),
            total: isset($data['total']) ? Money::fromArray($data['total']) : Money::fromArray([]),
            shippingAddress: isset($data['shippingAddress']) ? Address::fromArray($data['shippingAddress']) : null,
            notes: $data['notes'] ?? null,
        );

        return $instance;
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromRequestArray(array $data): Order
    {
        return Order::fromArray($data);
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromResponseArray(array $data): Order
    {
        return Order::fromArray($data);
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toArray(): array
    {
        $data = [];
        $data['id'] = $this->id;
        $data['status'] = $this->status->toArray();
        $data['total'] = method_exists($this->total, 'toArray') ? $this->total->toArray() : $this->total;
        if ($this->shippingAddress !== null) {
            $data['shippingAddress'] = method_exists($this->shippingAddress, 'toArray') ? $this->shippingAddress->toArray() : $this->shippingAddress;
        }
        if ($this->notes !== null) {
            $data['notes'] = $this->notes;
        }

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toRequestArray(): array
    {
        $data = $this->toArray();

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toResponseArray(): array
    {
        $data = $this->toArray();

        return $data;
    }

    /**
     * Returns Laravel validation rules for this model.
     *
     * @return array<string, string|array<string>>
     */
    public static function rules(): array
    {
        $rules = [
            'id' => ['required', 'string', 'uuid'],
            'status' => ['required'],
            'total' => ['required'],
            'shippingAddress' => ['nullable'],
            'notes' => ['nullable', 'string'],
        ];
        foreach (Money::rules() as $nestedKey => $nestedRules) {
            $rules['total' . '.' . $nestedKey] = $nestedRules;
        }
        foreach (Address::rules() as $nestedKey => $nestedRules) {
            $rules['shippingAddress' . '.' . $nestedKey] = $nestedRules;
        }

        return $rules;
    }

    /**
     * Returns Laravel validation rules for incoming request payloads.
     *
     * @return array<string, string|array<string>>
     */
    public static function requestRules(): array
    {
        $rules = [
            'id' => ['required', 'string', 'uuid'],
            'status' => ['required'],
            'total' => ['required'],
            'shippingAddress' => ['nullable'],
            'notes' => ['nullable', 'string'],
        ];
        foreach (Money::requestRules() as $nestedKey => $nestedRules) {
            $rules['total' . '.' . $nestedKey] = $nestedRules;
        }
        foreach (Address::requestRules() as $nestedKey => $nestedRules) {
            $rules['shippingAddress' . '.' . $nestedKey] = $nestedRules;
        }

        return $rules;
    }

    /**
     * Returns Laravel validation rules for outgoing response payloads.
     *
     * @return array<string, string|array<string>>
     */
    public static function responseRules(): array
    {
        $rules = [
            'id' => ['required', 'string', 'uuid'],
            'status' => ['required'],
            'total' => ['required'],
            'shippingAddress' => ['nullable'],
            'notes' => ['nullable', 'string'],
        ];
        foreach (Money::responseRules() as $nestedKey => $nestedRules) {
            $rules['total' . '.' . $nestedKey] = $nestedRules;
        }
        foreach (Address::responseRules() as $nestedKey => $nestedRules) {
            $rules['shippingAddress' . '.' . $nestedKey] = $nestedRules;
        }

        return $rules;
    }
}
