<?php

declare(strict_types=1);

namespace Generated\Model;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator dev-main (<normalized timestamp>)
 */

/**
 * Numeric priority level.
 */
enum Priority: int
{
    case Value1 = 1;
    case Value2 = 2;
    case Value3 = 3;

    public static function fromArray(mixed $value): ?Priority
    {
        if (!is_int($value) && !is_string($value)) {
            return null;
        }
        if (is_string($value) && !is_numeric($value)) {
            return null;
        }
        $value = (int) $value;

        return Priority::tryFrom($value);
    }

    public function toArray(): int
    {
        return $this->value;
    }
}
