<?php

declare(strict_types=1);

namespace MaxBeckers\OpenApiGenerator\Tests\Integration;

use MaxBeckers\OpenApiGenerator\Config\GeneratorConfig;
use MaxBeckers\OpenApiGenerator\Config\ValidationStrategy;
use MaxBeckers\OpenApiGenerator\FileWriter\FileWriter;
use MaxBeckers\OpenApiGenerator\Loader\OpenApiLoader;
use MaxBeckers\OpenApiGenerator\Service\OpenApiService;
use PHPUnit\Framework\TestCase;

class ModelGenerationTest extends TestCase
{
    private string $outputDir;
    private static OpenApiService $sharedService;

    public static function setUpBeforeClass(): void
    {
        self::$sharedService = new OpenApiService(new OpenApiLoader(), new FileWriter());
    }

    protected function setUp(): void
    {
        $this->outputDir = sys_get_temp_dir() . '/openapi-gen-test-' . uniqid('', true);
    }

    protected function tearDown(): void
    {
        $this->removeDir($this->outputDir);
    }

    public function testGeneratesModelsFromPetstore(): void
    {
        $config = $this->makeConfig();
        $config->classSuffix = '';
        $config->generateFromArray = true;
        $config->generateToArray = true;
        $config->phpReadonly = true;

        $service = self::$sharedService;
        $service->generate($config, self::FIXTURES_DIR);

        $modelDir = $this->outputDir . '/Model';

        self::assertDirectoryExists($modelDir);
        self::assertFileExists($modelDir . '/Pet.php');
        self::assertFileExists($modelDir . '/NewPet.php');
        self::assertFileExists($modelDir . '/PetStatus.php');
        // Pets is an array schema → Alias kind, no file generated
        self::assertFileDoesNotExist($modelDir . '/Pets.php');
    }

    public function testGeneratedPetClassHasCorrectStructure(): void
    {
        $config = $this->makeConfig();

        $service = self::$sharedService;
        $service->generate($config, self::FIXTURES_DIR);

        $content = file_get_contents($this->outputDir . '/Model/Pet.php');

        self::assertStringContainsString('namespace Generated\\Model;', $content);
        self::assertStringContainsString('readonly class Pet', $content);
        self::assertStringContainsString('public int $id', $content);
        self::assertStringContainsString('public string $name', $content);
        self::assertStringContainsString('public static function fromArray', $content);
        self::assertStringContainsString('public function toArray', $content);
        self::assertStringContainsString("\n * @generated by maxbeckers/php-openapi-generator", $content);
        self::assertStringNotContainsString("\n  * @generated by maxbeckers/php-openapi-generator", $content);
    }

    public function testGeneratedPetStatusIsEnum(): void
    {
        $config = $this->makeConfig();

        $service = self::$sharedService;
        $service->generate($config, self::FIXTURES_DIR);

        $content = file_get_contents($this->outputDir . '/Model/PetStatus.php');

        self::assertStringContainsString('enum PetStatus: string', $content);
        self::assertStringContainsString("case Available = 'available';", $content);
        self::assertStringContainsString("case Pending = 'pending';", $content);
        self::assertStringContainsString("case Sold = 'sold';", $content);
        self::assertStringContainsString('public static function fromArray', $content);
    }

    public function testReadOnlyWriteOnlyDirectionalArrayMethodsAreGenerated(): void
    {
        $config = $this->makeConfig('read-write-flags.yaml');

        $service = self::$sharedService;
        $service->generate($config, self::FIXTURES_DIR);

        $content = file_get_contents($this->outputDir . '/Model/Account.php');

        self::assertStringContainsString('public static function fromRequestArray(array $data): static', $content);
        self::assertStringContainsString("unset(\$data['id']);", $content);
        self::assertStringContainsString('public static function fromResponseArray(array $data): static', $content);
        self::assertStringContainsString("unset(\$data['password']);", $content);
        self::assertStringContainsString('public function toRequestArray(): array', $content);
        self::assertStringContainsString('public function toResponseArray(): array', $content);
    }

    public function testReadOnlyWriteOnlyDirectionalArrayMethodsWorkAtRuntime(): void
    {
        $config = $this->makeConfig('read-write-flags.yaml');

        $service = self::$sharedService;
        $service->generate($config, self::FIXTURES_DIR);

        $script = <<<'PHP'
require __ACCOUNT_FILE__;

$request = \Generated\Model\Account::fromRequestArray([
    'id' => 123,
    'name' => 'Alice',
    'password' => 'secret123',
]);

$response = \Generated\Model\Account::fromResponseArray([
    'id' => 456,
    'name' => 'Bob',
    'password' => 'should-be-ignored',
]);

echo json_encode([
    'requestArray' => $request->toRequestArray(),
    'requestId' => $request->id,
    'responseArray' => $response->toResponseArray(),
    'responsePassword' => $response->password,
], JSON_THROW_ON_ERROR);
PHP;

        $script = str_replace('__ACCOUNT_FILE__', var_export($this->outputDir . '/Model/Account.php', true), $script);
        $output = $this->runPhpScript($script);

        $result = json_decode(trim($output), true, 512, JSON_THROW_ON_ERROR);

        self::assertArrayNotHasKey('id', $result['requestArray']);
        self::assertSame('Alice', $result['requestArray']['name']);
        self::assertSame('secret123', $result['requestArray']['password']);
        self::assertSame(0, $result['requestId']);
        self::assertSame(456, $result['responseArray']['id']);
        self::assertSame('Bob', $result['responseArray']['name']);
        self::assertArrayNotHasKey('password', $result['responseArray']);
        self::assertSame('', $result['responsePassword']);
    }

    public function testGeneratedFilesAreValidPhp(): void
    {
        $config = $this->makeConfig();

        $service = self::$sharedService;
        $service->generate($config, self::FIXTURES_DIR);

        $modelDir = $this->outputDir . '/Model';
        foreach (glob($modelDir . '/*.php') as $file) {
            $output = shell_exec(PHP_BINARY . ' -l ' . escapeshellarg($file) . ' 2>&1');
            self::assertStringContainsString('No syntax errors', (string) $output, "Syntax error in $file");
        }
    }

    public function testClassSuffixApplied(): void
    {
        $config = $this->makeConfig();
        $config->classSuffix = 'Dto';

        $service = self::$sharedService;
        $service->generate($config, self::FIXTURES_DIR);

        $modelDir = $this->outputDir . '/Model';
        self::assertFileExists($modelDir . '/PetDto.php');
        self::assertStringContainsString('class PetDto', file_get_contents($modelDir . '/PetDto.php'));
    }

    public function testOperationFilterByTag(): void
    {
        $config = $this->makeConfig();
        $config->includeTags = ['pets'];

        $service = self::$sharedService;
        $service->generate($config, self::FIXTURES_DIR);

        // All petstore tags are 'pets', so all models should still be generated
        self::assertFileExists($this->outputDir . '/Model/Pet.php');
    }

    public function testSymfonyValidationAttributesAreGenerated(): void
    {
        $config = $this->makeConfig();
        $config->validationStrategy = ValidationStrategy::SymfonyConstraints;

        $service = self::$sharedService;
        $service->generate($config, self::FIXTURES_DIR);

        $content = file_get_contents($this->outputDir . '/Model/Pet.php');

        self::assertStringContainsString('use Symfony\\Component\\Validator\\Constraints as Assert;', $content);
        self::assertStringContainsString('#[Assert\\NotNull(groups: ', $content);
        self::assertStringContainsString('#[Assert\\NotBlank(groups: ', $content);
        self::assertStringContainsString('#[Assert\\Length(min: 1, max: 100, groups: ', $content);
        self::assertStringContainsString('public function __construct(' . "\n\n" . '        #[Assert\\NotNull(groups: ', $content);
    }

    public function testNativeValidationMethodsAreGenerated(): void
    {
        $config = $this->makeConfig();
        $config->validationStrategy = ValidationStrategy::NativeMethod;

        $service = self::$sharedService;
        $service->generate($config, self::FIXTURES_DIR);

        $content = file_get_contents($this->outputDir . '/Model/Pet.php');

        self::assertStringNotContainsString('use Symfony\\Component\\Validator\\Constraints as Assert;', $content);
        self::assertStringContainsString('@return array<string>', $content);
        self::assertStringNotContainsString('@return list<string>', $content);
        self::assertStringContainsString('public function validate(): array', $content);
        self::assertStringContainsString('public function validateOrThrow(): void', $content);
        self::assertStringContainsString('$errors[] = \'name must not be blank.\';', $content);
        self::assertStringContainsString('$errors[] = \'name must have length >= 1.\';', $content);
        self::assertStringContainsString('$errors[] = \'name must have length <= 100.\';', $content);
        self::assertStringNotContainsString('$errors[] = \'id must not be null.\';' . "\n\n\n", $content);
    }

    public function testSymfonyValidationAttributesCoverAllValidationTypes(): void
    {
        $config = $this->makeConfig('validation-types.yaml');
        $config->validationStrategy = ValidationStrategy::SymfonyConstraints;

        $service = self::$sharedService;
        $service->generate($config, self::FIXTURES_DIR);

        $content = file_get_contents($this->outputDir . '/Model/ValidationSample.php');

        self::assertStringContainsString('#[Assert\\NotNull(groups: ', $content);
        self::assertStringContainsString('#[Assert\\NotBlank(groups: ', $content);
        self::assertStringContainsString('#[Assert\\Length(min: 1, max: 10, groups: ', $content);
        self::assertStringContainsString('#[Assert\\Regex(pattern: \'^[a-z]+$\', groups: ', $content);
        self::assertStringContainsString('#[Assert\\Range(min: 1, max: 9, groups: ', $content);
        self::assertStringContainsString('#[Assert\\DivisibleBy(value: 2, groups: ', $content);
        self::assertStringContainsString('#[Assert\\Count(min: 1, max: 3, groups: ', $content);
        self::assertStringContainsString('#[Assert\\Choice(choices: array (', $content);
        self::assertStringContainsString("0 => 'active'", $content);
        self::assertStringContainsString("1 => 'archived'", $content);
    }

    public function testNativeValidationMethodsCoverAllValidationTypes(): void
    {
        $config = $this->makeConfig('validation-types.yaml');
        $config->validationStrategy = ValidationStrategy::NativeMethod;

        $service = self::$sharedService;
        $service->generate($config, self::FIXTURES_DIR);

        $content = file_get_contents($this->outputDir . '/Model/ValidationSample.php');

        self::assertStringContainsString('$errors[] = \'requiredName must not be null.\';', $content);
        self::assertStringContainsString('$errors[] = \'requiredName must not be blank.\';', $content);
        self::assertStringContainsString('$errors[] = \'requiredName must have length >= 1.\';', $content);
        self::assertStringContainsString('$errors[] = \'requiredName must have length <= 10.\';', $content);
        self::assertStringContainsString('$errors[] = \'requiredName must match pattern ^[a-z]+$.\';', $content);
        self::assertStringContainsString('$errors[] = \'requiredNumber must be >= 1.\';', $content);
        self::assertStringContainsString('$errors[] = \'requiredNumber must be <= 9.\';', $content);
        self::assertStringContainsString('$errors[] = \'requiredNumber must be a multiple of 2.\';', $content);
        self::assertStringContainsString('$errors[] = \'scores must contain at least 1 item(s).\';', $content);
        self::assertStringContainsString('$errors[] = \'scores must contain at most 3 item(s).\';', $content);
        self::assertStringContainsString('$errors[] = \'state must be one of: active, archived.\';', $content);
    }

    public function testLaravelValidationRulesAreGenerated(): void
    {
        $config = $this->makeConfig();
        $config->validationStrategy = ValidationStrategy::LaravelValidation;

        $service = self::$sharedService;
        $service->generate($config, self::FIXTURES_DIR);

        $content = file_get_contents($this->outputDir . '/Model/Pet.php');

        self::assertStringNotContainsString('use Symfony\\Component\\Validator\\Constraints as Assert;', $content);
        self::assertStringContainsString('public static function rules(): array', $content);
        self::assertStringContainsString("'id' =>", $content);
        self::assertStringContainsString("'name' =>", $content);
        self::assertStringContainsString("'required'", $content);
        self::assertStringContainsString("'string'", $content);
        self::assertStringNotContainsString('array (', $content);
        self::assertStringContainsString("'id' => ['required', 'integer'],", $content);
        self::assertStringNotContainsString("]\n,", $content);
        self::assertStringNotContainsString("\n     * @generated by maxbeckers/php-openapi-generator", $content);
    }

    public function testDirectionalValidationIgnoresReadOnlyInRequestsAndWriteOnlyInResponses(): void
    {
        $config = $this->makeConfig('read-write-flags.yaml');
        $config->validationStrategy = ValidationStrategy::NativeMethod;

        $service = self::$sharedService;
        $service->generate($config, self::FIXTURES_DIR);

        $content = file_get_contents($this->outputDir . '/Model/Account.php');

        self::assertStringContainsString('public function validateForRequest(): array', $content);
        self::assertStringContainsString('public function validateForResponse(): array', $content);
        self::assertStringNotContainsString("id must not be null.';", $this->extractMethodBody($content, 'validateForRequest'));
        self::assertStringNotContainsString("password must not be null.';", $this->extractMethodBody($content, 'validateForResponse'));

        $script = <<<'PHP'
require __ACCOUNT_FILE__;

$request = \Generated\Model\Account::fromRequestArray([
    'name' => 'Alice',
    'password' => 'secret123',
]);

$response = \Generated\Model\Account::fromResponseArray([
    'id' => 42,
    'name' => 'Alice',
]);

echo json_encode([
    'requestErrors' => $request->validateForRequest(),
    'responseErrors' => $response->validateForResponse(),
], JSON_THROW_ON_ERROR);
PHP;

        $script = str_replace('__ACCOUNT_FILE__', var_export($this->outputDir . '/Model/Account.php', true), $script);
        $output = $this->runPhpScript($script);

        $result = json_decode(trim((string) $output), true, 512, JSON_THROW_ON_ERROR);
        self::assertSame([], $result['requestErrors']);
        self::assertSame([], $result['responseErrors']);
    }

    public function testLaravelDirectionalRulesExcludeReadOnlyAndWriteOnlyAsExpected(): void
    {
        $config = $this->makeConfig('read-write-flags.yaml');
        $config->validationStrategy = ValidationStrategy::LaravelValidation;

        $service = self::$sharedService;
        $service->generate($config, self::FIXTURES_DIR);

        $content = file_get_contents($this->outputDir . '/Model/Account.php');

        self::assertStringContainsString('public static function requestRules(): array', $content);
        self::assertStringContainsString('public static function responseRules(): array', $content);
        self::assertStringNotContainsString("'id' =>", $this->extractMethodBody($content, 'requestRules'));
        self::assertStringContainsString("'password' =>", $this->extractMethodBody($content, 'requestRules'));
        self::assertStringContainsString("'id' =>", $this->extractMethodBody($content, 'responseRules'));
        self::assertStringNotContainsString("'password' =>", $this->extractMethodBody($content, 'responseRules'));
    }

    public function testLaravelValidationRulesCoverAllValidationTypes(): void
    {
        $config = $this->makeConfig('validation-types.yaml');
        $config->validationStrategy = ValidationStrategy::LaravelValidation;

        $service = self::$sharedService;
        $service->generate($config, self::FIXTURES_DIR);

        $content = file_get_contents($this->outputDir . '/Model/ValidationSample.php');

        self::assertStringContainsString('public static function rules(): array', $content);
        self::assertStringContainsString("'required'", $content);
        self::assertStringContainsString("'nullable'", $content);
        self::assertStringContainsString("'string'", $content);
        self::assertStringContainsString("'min:", $content);
        self::assertStringContainsString("'max:", $content);
        self::assertStringContainsString("'regex:", $content);
        self::assertStringContainsString("'gte:", $content);
        self::assertStringContainsString("'lte:", $content);
        self::assertStringContainsString("'in:", $content);
        self::assertStringContainsString("'integer'", $content);
        self::assertStringContainsString("'array'", $content);
        self::assertStringContainsString("'multiple_of:", $content);
    }

    private function makeConfig(string $specFile = 'petstore.yaml'): GeneratorConfig
    {
        $config = new GeneratorConfig();
        $config->specFile = $specFile;
        $config->outputDir = $this->outputDir;
        $config->modelNamespace = 'Generated\\Model';
        $config->modelOutputDir = 'Model';
        $config->phpVersion = '8.2';

        return $config;
    }

    private const FIXTURES_DIR = __DIR__ . '/../Fixtures';

    private function removeDir(string $dir): void
    {
        if (!is_dir($dir)) {
            return;
        }
        $files = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::CHILD_FIRST
        );
        foreach ($files as $file) {
            $file->isDir() ? rmdir($file->getRealPath()) : unlink($file->getRealPath());
        }
        rmdir($dir);
    }

    private function extractMethodBody(string $content, string $methodName): string
    {
        $start = strpos($content, 'function ' . $methodName . '(');
        self::assertNotFalse($start, 'Method ' . $methodName . ' not found.');

        $next = strpos($content, "\n    public function ", $start + 1);
        if ($next === false) {
            $next = strpos($content, "\n    public static function ", $start + 1);
        }
        if ($next === false) {
            $next = strrpos($content, "\n}");
        }

        return substr($content, $start, $next - $start);
    }

    private function runPhpScript(string $script): string
    {
        $scriptFile = tempnam(sys_get_temp_dir(), 'openapi-gen-runtime-');
        self::assertNotFalse($scriptFile);

        file_put_contents($scriptFile, "<?php\n" . $script);

        try {
            $output = shell_exec(PHP_BINARY . ' ' . escapeshellarg($scriptFile) . ' 2>&1');
            self::assertNotFalse($output);

            return trim((string) $output);
        } finally {
            if (is_file($scriptFile)) {
                unlink($scriptFile);
            }
        }
    }
}
