<?php

declare(strict_types=1);

namespace MaxBeckers\OpenApiGenerator\Tests\Integration;

use MaxBeckers\OpenApiGenerator\Config\GenerationTarget;
use MaxBeckers\OpenApiGenerator\Config\GeneratorConfig;
use MaxBeckers\OpenApiGenerator\FileWriter\FileWriter;
use MaxBeckers\OpenApiGenerator\Loader\OpenApiLoader;
use MaxBeckers\OpenApiGenerator\Service\OpenApiService;
use PHPUnit\Framework\TestCase;

class SplitSpecGenerationTest extends TestCase
{
    private string $outputDirectory;
    private string $bundledOutputDirectory;

    protected function setUp(): void
    {
        $this->outputDirectory = sys_get_temp_dir() . '/openapi-split-' . uniqid('', true);
        $this->bundledOutputDirectory = sys_get_temp_dir() . '/openapi-bundled-' . uniqid('', true);
    }

    protected function tearDown(): void
    {
        $this->removeDirectory($this->outputDirectory);
        $this->removeDirectory($this->bundledOutputDirectory);
    }

    public function testGeneratesModelsAndApiFromSplitSpecification(): void
    {
        (new OpenApiService(new OpenApiLoader(), new FileWriter()))->generate(
            $this->makeConfig('split-spec/openapi.yaml', $this->outputDirectory),
            __DIR__ . '/../Fixtures',
        );

        self::assertFileExists($this->outputDirectory . '/Model/User.php');
        self::assertFileExists($this->outputDirectory . '/Model/Address.php');
        self::assertFileExists($this->outputDirectory . '/Api/UsersApiInterface.php');

        $user = (string) file_get_contents($this->outputDirectory . '/Model/User.php');
        self::assertStringContainsString('Address $address', $user);

        $api = (string) file_get_contents($this->outputDirectory . '/Api/UsersApiInterface.php');
        self::assertStringContainsString('function getUser(int $userId, ?bool $verbose', $api);
        self::assertStringContainsString(': User;', $api);
        self::assertStringContainsString('function updateUser(int $userId, User $body)', $api);
    }

    public function testSplitSpecGeneratesTheSamePhpAsBundledSpec(): void
    {
        $service = new OpenApiService(new OpenApiLoader(), new FileWriter());
        $service->generate(
            $this->makeConfig('split-spec/openapi.yaml', $this->outputDirectory),
            __DIR__ . '/../Fixtures',
        );
        $service->generate(
            $this->makeConfig('split-spec-bundled.yaml', $this->bundledOutputDirectory),
            __DIR__ . '/../Fixtures',
        );

        foreach ([
            '/Model/User.php',
            '/Model/Address.php',
            '/Model/EscapedPointer.php',
            '/Api/UsersApiInterface.php',
        ] as $relativePath) {
            self::assertFileExists($this->outputDirectory . $relativePath);
            self::assertFileExists($this->bundledOutputDirectory . $relativePath);
            self::assertSame(
                $this->withoutGenerationTimestamp((string) file_get_contents($this->bundledOutputDirectory . $relativePath)),
                $this->withoutGenerationTimestamp((string) file_get_contents($this->outputDirectory . $relativePath)),
                sprintf('Generated file %s differs from the bundled equivalent.', $relativePath),
            );
        }
    }

    private function makeConfig(string $specFile, string $outputDirectory): GeneratorConfig
    {
        $config = new GeneratorConfig();
        $config->specFile = $specFile;
        $config->outputDir = $outputDirectory;
        $config->modelNamespace = 'App\\Model';
        $config->modelOutputDir = 'Model';
        $config->apiNamespace = 'App\\Api';
        $config->apiOutputDir = 'Api';
        $config->generationTarget = GenerationTarget::Server;

        return $config;
    }

    private function withoutGenerationTimestamp(string $contents): string
    {
        return preg_replace('/^ \* @generated by .*$/m', '', $contents) ?? $contents;
    }

    private function removeDirectory(string $directory): void
    {
        if (!is_dir($directory)) {
            return;
        }

        foreach (scandir($directory) ?: [] as $item) {
            if ($item === '.' || $item === '..') {
                continue;
            }

            $path = $directory . DIRECTORY_SEPARATOR . $item;
            if (is_dir($path)) {
                $this->removeDirectory($path);
            } else {
                unlink($path);
            }
        }

        rmdir($directory);
    }
}
