<?php

declare(strict_types=1);

namespace Generated\Model;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator <normalized version> (<normalized timestamp>)
 */

readonly class Order
{
    public function __construct(
        public string $id,
        public OrderStatus $status,
        public Money $total,
        public ?Address $shippingAddress = null,
        public ?string $notes = null,
    ) {}

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromArray(array $data): Order
    {
        $instance = new Order(
            id: $data['id'] ?? '',
            status: isset($data['status'])
                ? (OrderStatus::fromArray($data['status']) ?? throw new \InvalidArgumentException('Unknown value for status.'))
                : throw new \InvalidArgumentException('Missing required property status.'),
            total: isset($data['total']) ? Money::fromArray($data['total']) : Money::fromArray([]),
            shippingAddress: isset($data['shippingAddress']) ? Address::fromArray($data['shippingAddress']) : null,
            notes: $data['notes'] ?? null,
        );

        return $instance;
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromRequestArray(array $data): Order
    {
        return Order::fromArray($data);
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromResponseArray(array $data): Order
    {
        return Order::fromArray($data);
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toArray(): array
    {
        $data = [];
        $data['id'] = $this->id;
        $data['status'] = $this->status->toArray();
        $data['total'] = method_exists($this->total, 'toArray') ? $this->total->toArray() : $this->total;
        if ($this->shippingAddress !== null) {
            $data['shippingAddress'] = method_exists($this->shippingAddress, 'toArray') ? $this->shippingAddress->toArray() : $this->shippingAddress;
        }
        if ($this->notes !== null) {
            $data['notes'] = $this->notes;
        }

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toRequestArray(): array
    {
        $data = $this->toArray();

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toResponseArray(): array
    {
        $data = $this->toArray();

        return $data;
    }

    /**
     * @return array<string>
     */
    public function validate(): array
    {
        $errors = [];
        if (preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i', $this->id) !== 1) {
            $errors[] = 'id must be a valid UUID.';
        }
        foreach ($this->total->validate() as $nestedError) {
            $errors[] = 'total.' . $nestedError;
        }
        if ($this->shippingAddress !== null) {
            foreach ($this->shippingAddress->validate() as $nestedError) {
                $errors[] = 'shippingAddress.' . $nestedError;
            }
        }

        return $errors;
    }

    /**
     * @return array<string>
     */
    public function validateForRequest(): array
    {
        $errors = [];
        if (preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i', $this->id) !== 1) {
            $errors[] = 'id must be a valid UUID.';
        }
        foreach ($this->total->validate() as $nestedError) {
            $errors[] = 'total.' . $nestedError;
        }
        if ($this->shippingAddress !== null) {
            foreach ($this->shippingAddress->validate() as $nestedError) {
                $errors[] = 'shippingAddress.' . $nestedError;
            }
        }

        return $errors;
    }

    /**
     * @return array<string>
     */
    public function validateForResponse(): array
    {
        $errors = [];
        if (preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i', $this->id) !== 1) {
            $errors[] = 'id must be a valid UUID.';
        }
        foreach ($this->total->validate() as $nestedError) {
            $errors[] = 'total.' . $nestedError;
        }
        if ($this->shippingAddress !== null) {
            foreach ($this->shippingAddress->validate() as $nestedError) {
                $errors[] = 'shippingAddress.' . $nestedError;
            }
        }

        return $errors;
    }

    public function validateOrThrow(): void
    {
        $errors = $this->validate();
        if ($errors !== []) {
            throw new \InvalidArgumentException(implode('; ', $errors));
        }
    }

    public function validateOrThrowForRequest(): void
    {
        $errors = $this->validateForRequest();
        if ($errors !== []) {
            throw new \InvalidArgumentException(implode('; ', $errors));
        }
    }

    public function validateOrThrowForResponse(): void
    {
        $errors = $this->validateForResponse();
        if ($errors !== []) {
            throw new \InvalidArgumentException(implode('; ', $errors));
        }
    }
}
