<?php

declare(strict_types=1);

namespace Generated\Model;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator <normalized version> (<normalized timestamp>)
 */

readonly class OrphanSchema
{
    public function __construct(
        public ?string $value = null,
    ) {}

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromArray(array $data): OrphanSchema
    {
        $instance = new OrphanSchema(
            value: $data['value'] ?? null,
        );

        return $instance;
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromRequestArray(array $data): OrphanSchema
    {
        return OrphanSchema::fromArray($data);
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromResponseArray(array $data): OrphanSchema
    {
        return OrphanSchema::fromArray($data);
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toArray(): array
    {
        $data = [];
        if ($this->value !== null) {
            $data['value'] = $this->value;
        }

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toRequestArray(): array
    {
        $data = $this->toArray();

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toResponseArray(): array
    {
        $data = $this->toArray();

        return $data;
    }

    /**
     * @return array<string>
     */
    public function validate(): array
    {
        $errors = [];

        return $errors;
    }

    /**
     * @return array<string>
     */
    public function validateForRequest(): array
    {
        $errors = [];

        return $errors;
    }

    /**
     * @return array<string>
     */
    public function validateForResponse(): array
    {
        $errors = [];

        return $errors;
    }

    public function validateOrThrow(): void
    {
        $errors = $this->validate();
        if ($errors !== []) {
            throw new \InvalidArgumentException(implode('; ', $errors));
        }
    }

    public function validateOrThrowForRequest(): void
    {
        $errors = $this->validateForRequest();
        if ($errors !== []) {
            throw new \InvalidArgumentException(implode('; ', $errors));
        }
    }

    public function validateOrThrowForResponse(): void
    {
        $errors = $this->validateForResponse();
        if ($errors !== []) {
            throw new \InvalidArgumentException(implode('; ', $errors));
        }
    }
}
