<?php

declare(strict_types=1);

namespace Generated\Api;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator <normalized version> (<normalized timestamp>)
 */

abstract class CatalogApiController implements CatalogApiInterface
{
    public function listCatalogItemsAction(\Illuminate\Http\Request $request): \Illuminate\Http\JsonResponse
    {
        $result = $this->listCatalogItems(
        );

        return new \Illuminate\Http\JsonResponse(array_map(static fn($item) => is_object($item) && method_exists($item, 'toResponseArray') ? $item->toResponseArray() : (is_object($item) && method_exists($item, 'toArray') ? $item->toArray() : $item), $result), 200);
    }

    /**
     * List catalog items
     * @return list<\Generated\Model\CatalogItem>
     */
    public function listCatalogItems(): array
    {
        throw new \BadMethodCallException('Override listCatalogItems() or listCatalogItemsAction() to implement this operation.');
    }
}
