<?php

declare(strict_types=1);

namespace Generated\Api;

use Generated\Model\CreateOrderRequest;
use Generated\Model\Order;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator dev-main (<normalized timestamp>)
 */

interface OrdersApiInterface
{
    /**
     * Create an order
     */
    public function createOrder(CreateOrderRequest $body): Order;
}
