<?php

declare(strict_types=1);

namespace Generated\Api;

use Generated\Model\CreateOrderRequest;
use Generated\Model\Order;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Validator\Validation;
use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator <normalized version> (<normalized timestamp>)
 */

abstract class OrdersApiController implements OrdersApiInterface
{
    private readonly ValidatorInterface $validator;

    public function __construct(?ValidatorInterface $validator = null)
    {
        $this->validator = $validator ?? Validation::createValidatorBuilder()
            ->enableAttributeMapping()
            ->getValidator();
    }

    /**
     * @param \SplObjectStorage<object, mixed>|null $visited
     */
    private function validateSymfonyRequestPayload(mixed $value, ?\SplObjectStorage $visited = null): void
    {
        if (!is_array($value) && !is_object($value)) {
            return;
        }

        $visited ??= new \SplObjectStorage();

        if (is_object($value)) {
            if ($visited->contains($value)) {
                return;
            }
            $visited->attach($value);

            $violations = $this->validator->validate($value, groups: ['request']);
            if (count($violations) > 0) {
                throw new \InvalidArgumentException((string) $violations);
            }

            foreach (get_object_vars($value) as $propertyValue) {
                $this->validateSymfonyRequestPayload($propertyValue, $visited);
            }

            return;
        }

        foreach ($value as $item) {
            $this->validateSymfonyRequestPayload($item, $visited);
        }
    }

    /**
     * @param \SplObjectStorage<object, mixed>|null $visited
     */
    private function validateSymfonyResponsePayload(mixed $value, ?\SplObjectStorage $visited = null): void
    {
        if (!is_array($value) && !is_object($value)) {
            return;
        }

        $visited ??= new \SplObjectStorage();

        if (is_object($value)) {
            if ($visited->contains($value)) {
                return;
            }
            $visited->attach($value);

            $violations = $this->validator->validate($value, groups: ['response']);
            if (count($violations) > 0) {
                throw new \InvalidArgumentException((string) $violations);
            }

            foreach (get_object_vars($value) as $propertyValue) {
                $this->validateSymfonyResponsePayload($propertyValue, $visited);
            }

            return;
        }

        foreach ($value as $item) {
            $this->validateSymfonyResponsePayload($item, $visited);
        }
    }

    /**
     * Decodes the JSON request body and hydrates it with the given factory.
     *
     * @template T of object
     *
     * @param \Closure(array<array-key, mixed>): T $factory
     *
     * @throws \Symfony\Component\HttpKernel\Exception\BadRequestHttpException when the body is missing, malformed or cannot be hydrated
     *
     * @return ($required is true ? T : T|null)
     */
    protected function parseJsonRequestBody(Request $request, \Closure $factory, bool $required = true): ?object
    {
        $content = $request->getContent();
        if (trim($content) === '') {
            if ($required) {
                throw new \Symfony\Component\HttpKernel\Exception\BadRequestHttpException('Request body is required.');
            }

            return null;
        }

        try {
            $data = json_decode($content, true, 512, JSON_THROW_ON_ERROR);
        } catch (\JsonException $exception) {
            throw new \Symfony\Component\HttpKernel\Exception\BadRequestHttpException('Request body is not valid JSON.', $exception);
        }

        if (!is_array($data)) {
            throw new \Symfony\Component\HttpKernel\Exception\BadRequestHttpException('Request body must be a JSON object or array.');
        }

        try {
            return $factory($data);
        } catch (\InvalidArgumentException $exception) {
            throw new \Symfony\Component\HttpKernel\Exception\BadRequestHttpException('Invalid request body: ' . $exception->getMessage(), $exception);
        } catch (\TypeError|\ValueError $exception) {
            throw new \Symfony\Component\HttpKernel\Exception\BadRequestHttpException('Invalid request body.', $exception);
        }
    }

    #[Route('/orders', methods: ['POST'])]
    public function createOrderAction(Request $request): JsonResponse
    {
        $body = $this->parseJsonRequestBody($request, static fn(array $data): CreateOrderRequest => CreateOrderRequest::fromRequestArray($data));

        try {
            $this->validateSymfonyRequestPayload($body);
        } catch (\InvalidArgumentException $exception) {
            throw new \Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException($exception->getMessage(), $exception);
        }

        $result = $this->createOrder(
            body: $body,
        );
        $this->validateSymfonyResponsePayload($result);

        return new JsonResponse($result->toResponseArray(), 201);
    }

    /**
     * Create an order
     */
    public function createOrder(CreateOrderRequest $body): Order
    {
        throw new \BadMethodCallException('Override createOrder() or createOrderAction() to implement this operation.');
    }
}
