<?php

declare(strict_types=1);

namespace Generated\Model;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator <normalized version> (<normalized timestamp>)
 */

/**
 * A monetary amount.
 */
readonly class Money
{
    public function __construct(
        #[Assert\NotNull(groups: ['Default', 'request', 'response'])]
        /**
         * Amount in minor units.
         */
        public int $amount,
        #[Assert\NotNull(groups: ['Default', 'request', 'response'])]
        #[Assert\NotBlank(groups: ['Default', 'request', 'response'])]
        #[Assert\Length(min: 3, max: 3, groups: ['Default', 'request', 'response'])]
        /**
         * ISO 4217 currency code.
         */
        public string $currency,
    ) {}

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromArray(array $data): Money
    {
        $instance = new Money(
            amount: $data['amount'] ?? 0,
            currency: $data['currency'] ?? '',
        );

        return $instance;
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromRequestArray(array $data): Money
    {
        return Money::fromArray($data);
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromResponseArray(array $data): Money
    {
        return Money::fromArray($data);
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toArray(): array
    {
        $data = [];
        $data['amount'] = $this->amount;
        $data['currency'] = $this->currency;

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toRequestArray(): array
    {
        $data = $this->toArray();

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toResponseArray(): array
    {
        $data = $this->toArray();

        return $data;
    }
}
