<?php

declare(strict_types=1);

namespace Generated\Model;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator dev-main (<normalized timestamp>)
 */

readonly class PluginTestSchema
{
    public function __construct(
        #[Assert\NotNull(groups: ['Default', 'request', 'response'])]
        public string $name,
        #[Assert\NotNull(groups: ['Default', 'request', 'response'])]
        #[\SensitiveParameter]
        public string $password,
    ) {}

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromArray(array $data): PluginTestSchema
    {
        if (isset($data['name']) && is_string($data['name'])) {
            $data['name'] = substr($data['name'], 0, 30);
        }
        $instance = new PluginTestSchema(
            name: $data['name'] ?? '',
            password: $data['password'] ?? '',
        );

        return $instance;
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromRequestArray(array $data): PluginTestSchema
    {
        return PluginTestSchema::fromArray($data);
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromResponseArray(array $data): PluginTestSchema
    {
        return PluginTestSchema::fromArray($data);
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toArray(): array
    {
        $data = [];
        $data['name'] = $this->name;
        $data['password'] = $this->password;

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toRequestArray(): array
    {
        $data = $this->toArray();

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toResponseArray(): array
    {
        $data = $this->toArray();

        return $data;
    }
}
