<?php

declare(strict_types=1);

namespace Generated\Api;

use Generated\Model\CatalogItem;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator <normalized version> (<normalized timestamp>)
 */

final class CatalogApiClient implements CatalogApiClientInterface
{
    private function assertSuccessfulStatus(int $statusCode, string $operationId): void
    {
        if ($statusCode < 200 || $statusCode >= 300) {
            throw new \RuntimeException(sprintf(
                'API operation "%s" failed with HTTP status %d.',
                $operationId,
                $statusCode,
            ));
        }
    }

    private function decodeJsonResponse(string $contentType, string $body, string $operationId): mixed
    {
        if ($contentType !== '' && !str_contains(strtolower($contentType), 'json')) {
            throw new \UnexpectedValueException(sprintf(
                'Expected a JSON response for operation "%s", got content type "%s".',
                $operationId,
                $contentType,
            ));
        }

        try {
            return json_decode($body, true, 512, JSON_THROW_ON_ERROR);
        } catch (\JsonException $exception) {
            throw new \UnexpectedValueException(sprintf(
                'Invalid JSON response for operation "%s": %s',
                $operationId,
                $exception->getMessage(),
            ), 0, $exception);
        }
    }

    public function __construct(
        private readonly ClientInterface $httpClient,
        private readonly string $baseUrl,
        private readonly RequestFactoryInterface $requestFactory,
    ) {}

    /**
     * List catalog items
     * @return list<\Generated\Model\CatalogItem>
     */
    public function listCatalogItems(): array
    {
        $url = rtrim($this->baseUrl, '/') . '/catalog/items';
        $request = $this->requestFactory->createRequest('GET', $url);
        $response = $this->httpClient->sendRequest($request);
        $statusCode = $response->getStatusCode();
        $this->assertSuccessfulStatus($statusCode, 'listCatalogItems');
        $data = $this->decodeJsonResponse($response->getHeaderLine('Content-Type'), (string) $response->getBody(), 'listCatalogItems');
        if (!is_array($data) || !array_is_list($data)) {
            throw new \UnexpectedValueException('Expected a JSON array response for listCatalogItems.');
        }
        $result = [];
        foreach ($data as $item) {
            if (!is_array($item)) {
                throw new \UnexpectedValueException('Expected each listCatalogItems response item to be a JSON object.');
            }
            $result[] = CatalogItem::fromResponseArray($item);
        }

        return $result;
    }
}
