<?php

declare(strict_types=1);

namespace Generated\Api;

use Generated\Model\CreateOrderRequest;
use Generated\Model\Order;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\RequestOptions;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator <normalized version> (<normalized timestamp>)
 */

final class OrdersApiClient implements OrdersApiClientInterface
{
    private function assertSuccessfulStatus(int $statusCode, string $operationId): void
    {
        if ($statusCode < 200 || $statusCode >= 300) {
            throw new \RuntimeException(sprintf(
                'API operation "%s" failed with HTTP status %d.',
                $operationId,
                $statusCode,
            ));
        }
    }

    private function decodeJsonResponse(string $contentType, string $body, string $operationId): mixed
    {
        if ($contentType !== '' && !str_contains(strtolower($contentType), 'json')) {
            throw new \UnexpectedValueException(sprintf(
                'Expected a JSON response for operation "%s", got content type "%s".',
                $operationId,
                $contentType,
            ));
        }

        try {
            return json_decode($body, true, 512, JSON_THROW_ON_ERROR);
        } catch (\JsonException $exception) {
            throw new \UnexpectedValueException(sprintf(
                'Invalid JSON response for operation "%s": %s',
                $operationId,
                $exception->getMessage(),
            ), 0, $exception);
        }
    }

    public function __construct(
        private readonly ClientInterface $httpClient,
        private readonly string $baseUrl,
    ) {}

    /**
     * Create an order
     */
    public function createOrder(CreateOrderRequest $body): Order
    {
        $url = rtrim($this->baseUrl, '/') . '/orders';
        $options = [];
        $options[RequestOptions::JSON] = $body->toRequestArray();
        $options[RequestOptions::HTTP_ERRORS] = false;
        $response = $this->httpClient->request('POST', $url, $options);
        $statusCode = $response->getStatusCode();
        $this->assertSuccessfulStatus($statusCode, 'createOrder');
        $data = $this->decodeJsonResponse($response->getHeaderLine('Content-Type'), (string) $response->getBody(), 'createOrder');
        if (!is_array($data)) {
            throw new \UnexpectedValueException('Expected a JSON object response for createOrder.');
        }
        $result = Order::fromResponseArray($data);

        return $result;
    }
}
