<?php

declare(strict_types=1);

namespace Generated\Api;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator <normalized version> (<normalized timestamp>)
 */

interface CatalogApiInterface
{
    /**
     * List catalog items
     * @return list<\Generated\Model\CatalogItem>
     */
    public function listCatalogItems(): array;
}
