<?php

declare(strict_types=1);

namespace Generated\Api;

use Illuminate\Support\Facades\Route;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator dev-main (<normalized timestamp>)
 */
final class CatalogApiRoutes
{
    private function __construct() {}

    public static function register(string $controller = CatalogApiController::class): void
    {
        Route::get('/catalog/items', [$controller, 'listCatalogItemsAction']);
    }
}
