<?php

declare(strict_types=1);

namespace Generated\Api;

use Generated\Model\CreateOrderRequest;
use Generated\Model\Order;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator dev-main (<normalized timestamp>)
 */

abstract class OrdersApiController implements OrdersApiInterface
{
    private function validateLaravelRequestPayload(mixed $value): void
    {
        if (is_array($value)) {
            foreach ($value as $item) {
                $this->validateLaravelRequestPayload($item);
            }

            return;
        }

        if (!is_object($value)) {
            return;
        }

        $class = $value::class;
        if (!method_exists($class, 'requestRules')) {
            return;
        }

        $validator = \Illuminate\Support\Facades\Validator::make(
            method_exists($value, 'toRequestArray')
                ? $value->toRequestArray()
                : (method_exists($value, 'toArray') ? $value->toArray() : get_object_vars($value)),
            $class::requestRules(),
        );

        if ($validator->fails()) {
            throw new \Illuminate\Validation\ValidationException($validator);
        }

        foreach (get_object_vars($value) as $propertyValue) {
            $this->validateLaravelRequestPayload($propertyValue);
        }
    }

    private function validateLaravelResponsePayload(mixed $value): void
    {
        if (is_array($value)) {
            foreach ($value as $item) {
                $this->validateLaravelResponsePayload($item);
            }

            return;
        }

        if (!is_object($value)) {
            return;
        }

        $class = $value::class;
        if (!method_exists($class, 'responseRules')) {
            return;
        }

        $validator = \Illuminate\Support\Facades\Validator::make(
            method_exists($value, 'toResponseArray')
                ? $value->toResponseArray()
                : (method_exists($value, 'toArray') ? $value->toArray() : get_object_vars($value)),
            $class::responseRules(),
        );

        if ($validator->fails()) {
            throw new \InvalidArgumentException('Validation failed: ' . $validator->errors());
        }

        foreach (get_object_vars($value) as $propertyValue) {
            $this->validateLaravelResponsePayload($propertyValue);
        }
    }

    /**
     * Decodes the JSON request body and hydrates it with the given factory.
     *
     * @template T of object
     *
     * @param \Closure(array<array-key, mixed>): T $factory
     *
     * @throws \Symfony\Component\HttpKernel\Exception\BadRequestHttpException when the body is missing, malformed or cannot be hydrated
     *
     * @return ($required is true ? T : T|null)
     */
    protected function parseJsonRequestBody(\Illuminate\Http\Request $request, \Closure $factory, bool $required = true): ?object
    {
        $content = $request->getContent();
        if (trim($content) === '') {
            if ($required) {
                throw new \Symfony\Component\HttpKernel\Exception\BadRequestHttpException('Request body is required.');
            }

            return null;
        }

        try {
            $data = json_decode($content, true, 512, JSON_THROW_ON_ERROR);
        } catch (\JsonException $exception) {
            throw new \Symfony\Component\HttpKernel\Exception\BadRequestHttpException('Request body is not valid JSON.', $exception);
        }

        if (!is_array($data)) {
            throw new \Symfony\Component\HttpKernel\Exception\BadRequestHttpException('Request body must be a JSON object or array.');
        }

        try {
            return $factory($data);
        } catch (\InvalidArgumentException $exception) {
            throw new \Symfony\Component\HttpKernel\Exception\BadRequestHttpException('Invalid request body: ' . $exception->getMessage(), $exception);
        } catch (\TypeError|\ValueError $exception) {
            throw new \Symfony\Component\HttpKernel\Exception\BadRequestHttpException('Invalid request body.', $exception);
        }
    }

    public function createOrderAction(\Illuminate\Http\Request $request): \Illuminate\Http\JsonResponse
    {
        $body = $this->parseJsonRequestBody($request, static fn(array $data): CreateOrderRequest => CreateOrderRequest::fromRequestArray($data));
        $this->validateLaravelRequestPayload($body);
        $result = $this->createOrder(
            body: $body,
        );
        $this->validateLaravelResponsePayload($result);

        return new \Illuminate\Http\JsonResponse($result->toResponseArray(), 201);
    }

    /**
     * Create an order
     */
    public function createOrder(CreateOrderRequest $body): Order
    {
        throw new \BadMethodCallException('Override createOrder() or createOrderAction() to implement this operation.');
    }
}
