<?php

declare(strict_types=1);

namespace Generated\Model;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator dev-main (<normalized timestamp>)
 */

/**
 * The order lifecycle status.
 */
enum OrderStatus: string
{
    case Pending = 'pending';
    case Confirmed = 'confirmed';
    case Shipped = 'shipped';
    case Cancelled = 'cancelled';

    public static function fromArray(mixed $value): ?OrderStatus
    {
        if (!is_scalar($value)) {
            return null;
        }
        $value = (string) $value;

        return OrderStatus::tryFrom($value);
    }

    public function toArray(): string
    {
        return $this->value;
    }
}
