<?php

declare(strict_types=1);

namespace Generated\Model;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator <normalized version> (<normalized timestamp>)
 */

readonly class Address
{
    public function __construct(
        public string $street,
        public string $city,
        /**
         * @deprecated
         */
        public ?string $oldZip = null,
        public ?string $postalCode = null,
    ) {}

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromArray(array $data): Address
    {
        $instance = new Address(
            street: $data['street'] ?? '',
            city: $data['city'] ?? '',
            oldZip: $data['oldZip'] ?? null,
            postalCode: $data['postalCode'] ?? null,
        );

        return $instance;
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromRequestArray(array $data): Address
    {
        return Address::fromArray($data);
    }

    /**
     * @param array<array-key, mixed> $data
     */
    public static function fromResponseArray(array $data): Address
    {
        return Address::fromArray($data);
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toArray(): array
    {
        $data = [];
        $data['street'] = $this->street;
        $data['city'] = $this->city;
        if ($this->oldZip !== null) {
            $data['oldZip'] = $this->oldZip;
        }
        if ($this->postalCode !== null) {
            $data['postalCode'] = $this->postalCode;
        }

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toRequestArray(): array
    {
        $data = $this->toArray();

        return $data;
    }

    /**
     * @return array<array-key, mixed>
     */
    public function toResponseArray(): array
    {
        $data = $this->toArray();

        return $data;
    }
}
