<?php

declare(strict_types=1);

namespace Generated\Api;

use Symfony\Component\Validator\Validation;
use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * This file was auto-generated by maxbeckers/php-openapi-generator.
 * Do not edit this file directly.
 * OpenAPI version: 3.0.0
 * API version: 1.0.0
 * @generated by maxbeckers/php-openapi-generator <normalized version> (<normalized timestamp>)
 */

abstract class CatalogApiController implements CatalogApiInterface
{
    private readonly ValidatorInterface $validator;

    public function __construct(?ValidatorInterface $validator = null)
    {
        $this->validator = $validator ?? Validation::createValidatorBuilder()
            ->enableAttributeMapping()
            ->getValidator();
    }

    /**
     * @param \SplObjectStorage<object, mixed>|null $visited
     */
    private function validateSymfonyResponsePayload(mixed $value, ?\SplObjectStorage $visited = null): void
    {
        if (!is_array($value) && !is_object($value)) {
            return;
        }

        $visited ??= new \SplObjectStorage();

        if (is_object($value)) {
            if ($visited->contains($value)) {
                return;
            }
            $visited->attach($value);

            $violations = $this->validator->validate($value, groups: ['response']);
            if (count($violations) > 0) {
                throw new \InvalidArgumentException((string) $violations);
            }

            foreach (get_object_vars($value) as $propertyValue) {
                $this->validateSymfonyResponsePayload($propertyValue, $visited);
            }

            return;
        }

        foreach ($value as $item) {
            $this->validateSymfonyResponsePayload($item, $visited);
        }
    }

    public function listCatalogItemsAction(\Illuminate\Http\Request $request): \Illuminate\Http\JsonResponse
    {
        $result = $this->listCatalogItems(
        );
        $this->validateSymfonyResponsePayload($result);

        return new \Illuminate\Http\JsonResponse(array_map(static fn($item) => is_object($item) && method_exists($item, 'toResponseArray') ? $item->toResponseArray() : (is_object($item) && method_exists($item, 'toArray') ? $item->toArray() : $item), $result), 200);
    }

    /**
     * List catalog items
     * @return list<\Generated\Model\CatalogItem>
     */
    public function listCatalogItems(): array
    {
        throw new \BadMethodCallException('Override listCatalogItems() or listCatalogItemsAction() to implement this operation.');
    }
}
